name: Java CI with Maven

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Run maven test
      run: mvn test

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Configure AWS CLI
      run: |
        aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws configure set region ap-south-1  # Update with your region if different

    - name: Upload WAR file to S3
      run: |
        aws s3 cp target/*.war s3://w20tfbackend/ROOT.war
