name: Deploy Maven Artifact

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set Up AWS Credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1

    - name: Set Up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.10.1

    

    - name: Initialize Terraform
      run: terraform -chdir=infra init -migrate-state

    - name: Refresh Terraform State
      run: terraform -chdir=infra refresh

    - name: Apply Terraform
      run: terraform -chdir=infra apply -auto-approve

    - name: Get EC2 Public IP
      id: get_ip
      run: |
        echo "ec2_ip=$(terraform output -raw ec2_public_ip)" >> $GITHUB_ENV
        terraform output -raw ec2_public_ip


    - name: Download WAR Artifact
      uses: actions/download-artifact@v3
      with:
        name: app.war

    - name: Upload WAR to EC2
      env:
        EC2_IP: ${{ steps.get_ip.outputs.ec2_ip }}
      run: |
        echo "${{ secrets.AWS_SSH_KEY }}" > ssh_key.pem
        chmod 600 ssh_key.pem
        scp -i ssh_key.pem app.war ubuntu@$EC2_IP:/opt/tomcat/webapps/
        ssh -i ssh_key.pem ubuntu@$EC2_IP "sudo systemctl restart tomcat.service"

    - name: Clean up SSH Key
      run: rm -f ssh_key.pem
