name: Another hello world

on:
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
    hello:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Greetings
              run: |
                pwd
                ls
                echo "Hello runner"
              shell: bash
    goodbye:
        runs-on: ubuntu-latest
        steps:
            - name: Good bye
              run: echo "Bye"



              
